name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  call-deploy:
    uses: leoserverteam/DevOpsTemplates/.github/workflows/onlycompose.yml@main
    with:
      project_name: "${{ github.event.repository.name }}"
  call-nginx:
    needs: [call-deploy]
    uses: leoserverteam/DevOpsTemplates/.github/workflows/deploynginx.yml@main
